version: '2'
volumes:
    shared-data:
    redis-data:
    web-data:
services:
  audio:
    restart: always
    image: bh.cr/balenalabs/audio-armv7hf
    privileged: true
    ports:
      - 4317:4317
  noise:
    restart: always
    build: ./noise
    privileged: true
    volumes:
      - 'shared-data:/data/my_data'
    ports:
      - "8080:8080"
    environment:
      PULSE_SERVER: tcp:audio:4317
  minio:
    restart: always
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    volumes:
      - 'shared-data:/data1'
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: myminio
      MINIO_SECRET_KEY: myminio123
      MINIO_REGION_NAME: myregion
    command: minio server /data1
  redis:
    restart: always
    image: redis:6.2.4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  webserver:
    restart: always
    build: ./webserver
    ports:
      - 80:80
    volumes:
      - 'shared-data:/data/my_data'
  controller:
    restart: always
    privileged: true
    build: ./controller
    volumes:
      - 'shared-data:/data/my_data'
    labels:
      io.balena.features.supervisor-api: '1'
